databases:
  - name: visiondata-db
    plan: free
    databaseName: visiondata
    user: visiondata

services:
  - type: web
    name: visiondata-web
    env: ruby
    plan: free
    buildCommand: |
      bundle install
      bundle exec rake assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    migrateCommand: bundle exec rails db:migrate db:seed
    autoDeploy: true
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: ACTIVE_STORAGE_SERVICE
        value: database
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: visiondata-db
          property: connectionString
